---
title: "Powerlifter EDA"
author: "smd"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
setwd("~/GitHub/powerlifting_eda")
library(tidyverse)
library(scales)
library(broom)

df <- read_csv("lifters.zip")
```


```{r}
lifters <- df %>% 
  mutate(year = year(date)) %>% 
  filter(year >= 2000) %>% 
  mutate(half_decade = (year %/% 5) * 5) %>% 
  mutate(decade = (year %/% 10) * 10) %>% 
  
  # making sure that I have all of the data required
  filter(!is.na(age)) %>% 
  filter(!is.na(best3squat_kg) & !is.na(best3bench_kg) & !is.na(best3deadlift_kg))
```

# Preliminaries

```{r}
lifters %>% 
  ggplot(aes(year)) + 
  geom_bar() +
  scale_y_continuous(labels = label_comma()) +
  labs(
    x = "",
    y = "",
    title = "Number of lifts over time"
  )
```

Let's start by seeing how the total weight lifted has chaned over time

```{r}
lifters %>% 
  ggplot(aes(as_factor(half_decade), total_kg)) +
  geom_boxplot() +
  labs(
    x = "Half Decade",
    y = "Total Lifted (kg)",
    title = "Have lifters gotten stronger with time?"
  )
  
```

Maybe... lets do a regression and see?

```{r}
mdl <- lm(lifters$total_kg ~ lifters$year)

tidy(mdl)

```



```{r}
lifters %>% 
  ggplot(aes(as_factor(half_decade), bodyweight_kg)) +
  geom_boxplot() +
  labs(
    x = "Half Decade",
    y = "Body Weight (kg)",
    title = "Have lifters gotten heavier with time?"
  )
  
```
Doesn't look it.  Let's just confirm with a quick regression...

```{r}
mdl <- lm(lifters$bodyweight_kg ~ lifters$year)
tidy(mdl)
```

I wonder what the impacts of aging on lifts are

```{r}
lifters %>% 
  ggplot(aes(age, total_kg)) + 
  geom_point() +
  geom_smooth() +
  labs(
    x = "Age",
    y = "Total Weight Lifter (kg)", 
    title = "How does age effect the amount that can be lifted?"
  )
```
It is a little assymetric... could I transform it into a parabola to make modeling easier

```{r}
lifters %>% 
  ggplot(aes(log10(age), total_kg)) + 
  geom_point() +
  geom_smooth() +
  labs(
    x = "log10(Age)",
    y = "Total Weight Lifter (kg)", 
    title = "How does age effect the amount that can be lifted?"
  )

```


```{r}
lifters %>% 
  select(age) %>% 
  arrange(desc(age))
```


```{r}
reg_data <- lifters %>% 
  select(total_kg, bodyweight_kg, age, year) %>% 
  mutate(log_lifted = log10(total_kg)) %>% 
  mutate(log_bodyweight = log10(bodyweight_kg)) %>% 
  mutate(log_age = log10(age)) %>% 
  mutate(squared_log_age = log10(age)^2)


mdl <- lm(total_kg ~ squared_log_age + log_age, data = tmp)

tidy(mdl)

```


```{r}
mdl <- lm(log_lifted ~ log_bodyweight + log_age + squared_log_age + year, data = reg_data)
tidy(mdl)
```

```{r}
summary(mdl)
```


